import type { Metadata } from "next";
import "./globals.css";
import { Inter, Rokkitt } from 'next/font/google'
import "../comps/editeur/schemas/nodes/temporary/globalNodeTemporary.css"
import { ClientSessionProvider } from "@/lib/SessionProvider";


// Inter → police par défaut
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

// Rokkitt → utilisée seulement à la demande
const rokkitt = Rokkitt({
  subsets: ["latin"],
  variable: "--font-rokkitt",
});

export const metadata: Metadata = {
  title: "Flashquizz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className={`${inter.variable} ${rokkitt.variable}`}>
      <ClientSessionProvider>
        <body className="font-sans">{children}</body>
      </ClientSessionProvider>
    </html>
  );
}
